import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/globals.css'
import '../styles/custom.scss'

// components
import SmoothScrollProvider from "@/components/context/SmoothScrollProvider";
import ClientProvider from "@/components/context/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <div id="content" className="h-full pt-24">
          <SmoothScrollProvider />
          <ClientProvider>
            {children}
          </ClientProvider>
        </div>
      </body>
    </html>
  );
}
